management:
#  contextPath: /manage
  context-path: /manage
#spring.datasource.platform = hsqldb

spring:
  datasource:
    platform: postgresql
    initialize: true

spring:
  jpa:
    generate-ddl: true
