management:
  context-path: /manage
#  contextPath: /manage

#spring.datasource.platform = hsqldb
spring:
  datasource:
    platform: postgresql
    initialize: true

spring:
  jpa:
    generate-ddl: true
