INSERT INTO PRODUCT (ID, NAME) VALUES (1, 'T-shirt');
INSERT INTO PRODUCT (ID, NAME) VALUES (2, 'Pants');
INSERT INTO PRODUCT (ID, NAME) VALUES (3, 'Sunglasses');
INSERT INTO PRODUCT (ID, NAME) VALUES (4, 'Watch');
INSERT INTO PRODUCT (ID, NAME) VALUES (5, 'iPhone');
INSERT INTO PRODUCT (ID, NAME) VALUES (6, 'Shirt');